"use client";
import Link from"next/link";import{FormEvent,useState}from"react";
const nav=["Menu","About","Gallery","Contact"];
function Head(){return <header className="border-b border-[#422c20]/10"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><Link href="/" className="font-serif text-3xl font-bold">Noura Café</Link><nav className="hidden gap-6 text-sm md:flex">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`}>{x}</Link>)}</nav><details className="relative md:hidden"><summary className="cursor-pointer list-none rounded-full bg-[#b6532f] px-3 py-2 text-xs font-bold text-white">Menu</summary><nav className="absolute right-0 z-10 mt-2 grid bg-[#422c20] p-3 text-white">{nav.map(x=><Link key={x} href={`/${x.toLowerCase()}`} className="px-3 py-2">{x}</Link>)}</nav></details></div></header>}
function Form(){const[s,setS]=useState(false);return <form onSubmit={(e:FormEvent)=>{e.preventDefault();setS(true)}} className="grid gap-4 rounded-3xl bg-[#b6532f] p-7 text-white"><input required aria-label="Name" placeholder="Your name" className="border-b border-white/30 bg-transparent py-3 outline-none"/><input required aria-label="Email" type="email" placeholder="Email address" className="border-b border-white/30 bg-transparent py-3 outline-none"/><select aria-label="Enquiry type" className="rounded-lg bg-white p-3 text-[#422c20]"><option>General enquiry</option><option>Group table enquiry</option><option>Private gathering</option></select><button className="w-fit rounded-full bg-[#f6d690] px-5 py-3 text-sm font-bold text-[#422c20]">{s?"Thanks — enquiry noted":"Send enquiry"}</button><p className="text-xs text-white/65">Demo form — no table is booked.</p></form>}
const d:Record<string,[string,string,string,React.ReactNode]>={
menu:["The menu","Comforting food, careful coffee, no rush.","A complete fictional menu structure designed for a local café website. Prices are illustrative only.",<div className="space-y-10">{[["Coffee & tea",[["Espresso","3.5"],["Cardamom latte","5.0"],["Pour over","5.5"],["Iced hibiscus tea","4.0"]]],["All-day plates",[["Labneh toast","8.0"],["Herb eggs","9.0"],["Seasonal grain bowl","11.0"],["Vegetable toastie","9.5"]]],["Sweet things",[["Olive-oil cake","6.0"],["Date cookie plate","5.0"],["Orange custard","6.5"]]]].map(([cat,items])=><section key={cat as string} className="grid gap-6 border-t border-[#422c20]/20 pt-7 md:grid-cols-[.35fr_.65fr]"><h2 className="font-serif text-4xl">{cat as string}</h2><div className="divide-y divide-[#422c20]/15">{(items as string[][]).map(([n,p])=><div key={n} className="flex justify-between gap-5 py-4"><div><p className="font-bold">{n}</p><p className="mt-1 text-sm text-[#795e4f]">Made fresh in this fictional concept kitchen.</p></div><p className="font-serif text-xl">{p}</p></div>)}</div></section>)}<p className="rounded-2xl bg-[#f6d690] p-5 text-sm leading-7">Please let the team know about allergies. This is a design demonstration, not a live ordering service.</p></div>],
about:["About Noura","A place to settle in, imagined with care.","A fictional café concept for slow mornings, shared lunches and a gentle end to the day.",<><div className="grid gap-8 md:grid-cols-2"><img src="https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1000&q=85" alt="Coffee at Noura" className="min-h-80 w-full object-cover"/><div className="flex flex-col justify-center"><h2 className="font-serif text-4xl">A local rhythm.</h2><p className="mt-5 leading-8 text-[#795e4f]">The concept pairs seasonal food with a calm, friendly setting and shows how a small-business site can communicate character without complex ordering technology.</p></div></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Morning","Coffee, pastry and the first hour."],["Midday","Simple plates and a sunny table."],["Evening","A final drink and something sweet."]].map(([t,c])=><article key={t} className="rounded-3xl bg-white p-7"><h2 className="font-serif text-3xl">{t}</h2><p className="mt-4 text-sm leading-7 text-[#795e4f]">{c}</p></article>)}</div></>],
gallery:["Gallery","A few moments from Noura.","Food, light and the small details that give a café its personality.",<div className="grid gap-5 md:grid-cols-12">{[["photo-1495474472287-4d71bcdd2085","md:col-span-7"],["photo-1515003197210-e0cd71810b5f","md:col-span-5"],["photo-1442512595331-e89e73853f31","md:col-span-5"],["photo-1498804103079-a6351b050096","md:col-span-7"]].map(([img,span])=><img key={img} src={`https://images.unsplash.com/${img}?auto=format&fit=crop&w=1100&q=85`} alt="Noura café detail" className={`h-80 w-full object-cover ${span}`}/>)}</div>],
contact:["Visit & contact","Come by when you can.","Hours, location and a clear path to send a café enquiry.",<div className="grid gap-10 md:grid-cols-2"><div className="rounded-3xl bg-white p-8"><p className="text-xs font-bold uppercase tracking-widest text-[#b6532f]">Noura Café</p><h2 className="mt-4 font-serif text-4xl">Old Market Quarter</h2><p className="mt-5 leading-8 text-[#795e4f]">Fictional location<br/>Mon–Fri 07:30–19:00<br/>Sat–Sun 08:00–18:00</p><a href="mailto:hello@nouracafe.demo" className="mt-7 inline-block font-bold underline">hello@nouracafe.demo</a><p className="mt-8 text-sm text-[#795e4f]">No live table booking or payment system is included.</p></div><Form/></div>]
};
export function Interior({page}:{page:string}){const s=d[page]??d.menu;return <main className="min-h-screen bg-[#f8f0e4] text-[#422c20]"><Head/><section className="mx-auto max-w-6xl px-6 py-16 md:py-24"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#b6532f]">{s[0]}</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[.95] md:text-8xl">{s[1]}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#795e4f]">{s[2]}</p><div className="mt-16">{s[3]}</div></section><section className="bg-[#b6532f] px-6 py-12 text-white"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-5 md:flex-row"><p className="font-serif text-3xl">Good coffee, good company.</p><Link href="/contact" className="w-fit rounded-full border border-white px-5 py-3">Plan a visit</Link></div></section><footer className="bg-[#422c20] px-6 py-10 text-[#f8f0e4]"><div className="mx-auto flex max-w-6xl justify-between"><p className="font-serif text-3xl">Noura Café</p><p className="text-sm text-white/60">Fictional café · Demo project</p></div></footer></main>}
